# Generated by Django 5.2.8 on 2025-11-08 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0002_series_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.series')),
            ],
            options={
                'ordering': ['series', 'season_number'],
                'unique_together': {('series', 'season_number')},
            },
        ),
    ]
