# Generated by Django 5.2.8 on 2025-11-08 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('episode_title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='season.season')),
            ],
            options={
                'ordering': ['season', 'episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
    ]
