# Generated by Django 5.2.8 on 2025-11-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='series', to='genre.genre'),
        ),
    ]
