# Generated by Django 5.2.8 on 2025-11-08 00:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('series', '0002_series_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(help_text='사용자의 닉네임', max_length=50, unique=True)),
                ('profile_image', models.ImageField(blank=True, help_text='프로필 이미지', null=True, upload_to='profile_images/')),
                ('kakao_id', models.CharField(blank=True, help_text='카카오 소셜 ID', max_length=100, null=True, unique=True)),
                ('is_kakao_user', models.BooleanField(default=False, help_text='카카오 로그인 사용자 여부')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WatchingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', '시청중'), ('completed', '시청완료'), ('plan_to_watch', '시청예정'), ('dropped', '시청중단')], help_text='시청 상태', max_length=20)),
                ('current_episode', models.IntegerField(default=0, help_text='현재 시청 중인 에피소드')),
                ('last_watched', models.DateTimeField(auto_now=True, help_text='마지막 시청일')),
                ('rating', models.IntegerField(blank=True, help_text='평점 (1-10)', null=True)),
                ('anime', models.ForeignKey(help_text='애니메이션', on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='series.series')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='watching_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '시청 현황',
                'verbose_name_plural': '시청 현황들',
                'db_table': 'watching_status',
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
