# Generated by Django 5.2.8 on 2025-11-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kakao_user',
            field=models.BooleanField(default=False, help_text='카카오 로그인 사용자 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(blank=True, help_text='카카오 소셜 ID', max_length=100, null=True, unique=True),
        ),
    ]
